# This is a basic workflow to help you get started with Actions

name: Angular Build
on: [workflow_dispatch]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node
        uses: actions/setup-node@v2.1.2
        with:
         node-version: '14.15.0'
      - name: Installing Packages
        run: npm install
      - run: npm link @angular/cli
      - name: Running the build
        run: ng build --prod
      - name: Collecting built files
        if: success() 
        uses: actions/upload-artifact@v2
        with:
         name: buildFiles
         path: dist/
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '5 minutes'
          skip-recent: 1
